title: Wendy Yuchen Sun 
email: wendyyuchensun@gmail.com 
description: Life of WebDev, Cooking & Reading Philosophy.
keywords: web development, cooking, philosophy 
url: "https://wendyyuchensun.github.io" 
author: Wendy Yuchen Sun
github_username:  wendyyuchensun
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

sass:
    sass_dir: _sass
