title: Wendy Yuchen Sun 
email: wendyyuchensun@gmail.com 
description: JavaScript, Cooking & Reading.
keywords: JavaScript, cooking, reading
url: "https://wendyyuchensun.github.io"
author: Wendy Yuchen Sun
github_username:  wendyyuchensun
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

sass:
    sass_dir: _sass
