title: Wendy Yuchen Sun 
email: wendyyuchensun@gmail.com 
description: Life of WebDev, Cooking & Reading Philosophy.
keywords: web development, cooking, philosophy 
url: "http://127.0.0.1:4000" 
author: Wendy Yuchen Sun
github_username:  wendyyuchensun
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

