title: Wendy Yuchen Sun 
email: wendyyuchensun@gmail.com 
description: Happy coding, DIY & cooking
keywords: JavaScript, web development, cooking, DIY
url: "https://wendyyuchensun.org"
author: Wendy Yuchen Sun
github_username:  wendyyuchensun
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

sass:
    sass_dir: _sass
    style: compact

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
