title: Wendy Yuchen Sun 
email: wendyyuchensun@gmail.cim 
description: Becoming a web developer
keywords: web development, JavaScript 
url: "http://127.0.0.1:4000" 
author: Wendy Yuchen Sun
github_username:  wendyyuchensun

