title: Wendy Yuchen Sun 
email: wendyyuchensun@gmail.cim 
description: Becoming a web developer
keywords: web development, JavaScript 
url: "https://wendyyuchensun.com" 
author: Wendy Yuchen Sun
github_username:  wendyyuchensun

