title: WYS 
email: wendyyuchensun@gmail.cim 
description: Becoming a web developer
keywords: web development, JavaScript 
url: "https://wendyyuchensun.github.io/" 
author: Wendy Yuchen Sun
github_username:  wendyyuchensun
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

